version: '3.7'

services:

  memsql:
    image: 'memsql/cluster-in-a-box'
    ports:
      - 3306:3306
      - 8080:8080
    environment:
      LICENSE_KEY: 'YOUR_LICENSE_KEY_HERE'
      START_AFTER_INIT: 'Y'

  # minio instances are load balanced behind nginx container
  minio:
    build:
      context: .
    ports:
      - "9000:9000"
    depends_on:
      - minio1
      - minio2

  minio1:
    image: minio/minio:RELEASE.2020-09-23T19-18-30Z
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: memsql # min 3 characters
      MINIO_SECRET_KEY: minio123 # min 8 characters
    command: server http://minio{1...2}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio:RELEASE.2020-09-23T19-18-30Z
    volumes:
      - data2-1:/data1
      - data2-2:/data2
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: memsql
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...2}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

# TODO: store in a more durable place
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
